# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 00:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', 'populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinfo',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='organizationinfo',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organizationinfo',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
