# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_open', models.DateTimeField()),
                ('hour_closed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('phone_number', models.TextField()),
                ('street', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('city', models.TextField(max_length=40)),
                ('state', models.TextField(max_length=40)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigator.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigator.Service'),
        ),
    ]
