# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models

def load_services(apps,schema_editor):
    Service=apps.get_model("navigator", "Service")
    services=['ACCESSIBILITY_SERVICES', 
              'ADULT_LITERACY', 
              'ART_THERAPY', 
              'ASSESSMENT',
              'BORROW_MATERIALS', 
              'CASE_MANAGEMENT', 
              'CHILD_CARE', 
              'CLOTHING', 
              'COMPUTERS', 
              'DENTAL_SERVICES', 
              'DOCUMENTATION_ASSISTANCE', 
              'DOMESTIC_VIOLENCE_SERVICES',
              'FOOD_GROCERIES', 
              'GROUPS', 
              'HAIRCUTS', 
              'HARM_REDUCTION', 
              'HIV_TESTING',
              'HOUSING', 
              'HOUSING_NAVIGATION',
              'INCOME_TAX_HELP', 
              'LAUNDRY', 
              'LEGAL_SERVICES',
              'LGBTQ_FOCUSED', 
              'LIBRARY_CARD', 
              'MAIL', 
              'MEALS',
              'MEDICAL_BENEFITS', 
              'MEDICAL_SERVICES', 
              'MENTAL_HEALTH', 
              'MINISTRY',
              'PHONE',
              'PUBLIC_RESTROOMS', 
              'REFRESHMENTS', 
              'SHOWERS', 
              'SNAP_FOOD_STAMPS', 
              'STORAGE', 
              'SUBSTANCE_ABUSE_TREATMENT',
              'SUPPORTED_EMPLOYMENT', 
              'TANF_FINANCIAL_ASSISTANCE', 
              'TRANSPORTATION', 
              'VOCATIONAL_TRAINING', 
              ]
    id=0
    for service in services:
        service_listed=Service(name=service,id=id)
        id=id+1
        service_listed.save()

def delete_services(apps,schema_editor):
    Service=apps.get_model("navigator","Service")
    Service.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [('navigator','0001_initial'),
    ]

    operations = [migrations.RunPython(load_services,delete_services),
    ]
